### ISSUE TITLE
How to limit the word counts？

### ISSUE THREAD

**Issue by wbtxd2004** [Viima/jquery-comments#10]
I am now using your comments framwork, it's really well. But I don't know how to limit the comment word counts and hope that you can help me solver this problem.

**Comment by jjtykkyl** [comment]
Maybe you could utilize the "postComment" and "putComment" callbacks for this purpose. What you could to is to check the length of the comment in those callbacks and then call "error" -callback if the comment was too long. It's also a good idea to notify the user that the comment was too long before calling the "error" callback.

**Comment by wbtxd2004** [comment]
Thanks! I will try as your said.
