### ISSUE TITLE
Not clear script

### ISSUE THREAD

**Issue by danman1234** [Viima/jquery-comments#103]
Hello, I am using this script, but do you have an example on how i can use it with callbacks to my php?
I have my own user table from mysql and if people logged in only that user can write a comment, but this script doesnt use php or any database.

do i have to echo js comments values with php?

var commentsArray = [  
{  
   "id": 1,
   "parent": null,
   "created": "2015-01-01",
   "modified": "2015-01-01",
   "content": "Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Sed posuere interdum sem. Quisque ligula eros ullamcorper quis, lacinia quis facilisis sed sapien. Mauris varius diam vitae arcu.",
   "pings": [],
   "creator": 6,
   "fullname": "Simon Powell",
   "profile_picture_url": "https://app.viima.com/static/media/user_profiles/user-icon.png",
   "created_by_admin": false,
   "created_by_current_user": false,
   "upvote_count": 3,
   "user_has_upvoted": false,
   "is_new": false
}

**Comment by burzum** [comment]
> do i have to echo js comments values with php?

Yes, you need an API that returns json data. The plugin can map your field names to the comments plugin, there is a map for that in the config. Read the docs. :)

**Comment by jessenieminen** [comment]
You might find this useful: http://viima.github.io/jquery-comments/#link-4

**Comment by luigi37** [comment]
Hi. Facing some troubles in understanding the logic.... 

I understood that, having already an user table in my mysql db,  I need to create a "comments" table which can replicate the "Fields" in http://viima.github.io/jquery-comments/#link-4

I understand that the plugin will handle all the retrieved comments as long as they are passed as jsonCOMMENT item.

I can't understand what are the endpoints here and what is the meaning of "customers" in the example...

Sorry, might be obvious but I'm struggling here...
