### ISSUE TITLE
Login with FB, Twitter, …

### ISSUE THREAD

**Issue by cbieser** [Viima/jquery-comments#11]
Add Login with Facebook, Twitter, Google and so on.

**Comment by jjtykkyl** [comment]
I understand your point about binding an authentication method with this commenting library. However, there is no way that this library could provide these login options out-of-the-box. First of all, you need to validate the user in your back-end as the data in front-end cannot be trusted as such. Second of all, these identity providers that you mentioned require an app to be registered in their developer portal. Thus there is no generic way to provide these login options.

**Comment by jjtykkyl** [comment]
If you want to provide these login options, I can recommend a front-end library called hello.js (https://adodson.com/hello.js/) that does most of the work for you. Still you need to register the applications for each identity provider.
