### ISSUE TITLE
Is there a template that I can edit to change the look and feel?

### ISSUE THREAD

**Issue by blimey85** [Viima/jquery-comments#112]
I really love the script but in order for it to match the rest of my site, I need to set it up with a much different look. Is there an easy way to do this or would it require making major changes to the script? I'm handy with JS so that wouldn't be a problem, but would make upgrading later problematic. Here is roughly the look I'm going for: http://demos.creative-tim.com/material-kit-pro/index.html#comments

**Comment by burzum** [comment]
No, there is no template. If you look at the code you'll see that the whole markup is built using Jquery methods. I would prefer to have some template as well but most stuff can be done using CSS anyway.

**Comment by blimey85** [comment]
Yea the CSS covers a lot but I'm wanting to do things like tooltips when you mouse over the profile image and other stuff. Would be easy if there was a template that was used. As-is you have to hack the code which is fine but prevents easily upgrading later.

**Comment by burzum** [comment]
You can fork it and pull changes back into your fork? I know it's no ideal but works.

**Comment by blimey85** [comment]
Yea, that's the plan.
