### ISSUE TITLE
Is this project still maintained?

### ISSUE THREAD

**Issue by burzum** [Viima/jquery-comments#115]
@jjtykkyl are you still alive?

If you don't have the time to maintain it anymore you might want to ask if somebody else wants to step in. And no, not me. I'm already involved in open source projects and maintain my own set of plugins. :)

**Comment by jessenieminen** [comment]
Hi @burzum,
Thanks for the concern! We're still maintaining the project as it's a core part of our product.

We've unfortunately been very busy with other development requirements as we've gained more and more customers and haven't thus had as much time for maintaining the project and engaging the community as we would've liked.

If there are volunteers interested in maintaining the project, we're glad to take people onboard, just let us know!
