### ISSUE TITLE
Server Side Logic

### ISSUE THREAD

**Issue by luigi37** [Viima/jquery-comments#120]
Hi. Facing some troubles in understanding the logic....

I understood that, having already an user table in my mysql db, I need to create a "comments" table which can replicate the "Fields" in http://viima.github.io/jquery-comments/#link-4

I understand that the plugin will handle all the retrieved comments as long as they are passed as jsonCOMMENT item.

I can't understand what are the endpoints here and what is the meaning of "customers" in the example...

Sorry, might be obvious but I'm struggling here...

**Comment by jessenieminen** [comment]
Hi @luigi37! Thanks for the message. 

The "customers" part in the documentation refers to the fact that the product where we use this library is multitenant SaaS, meaning that we serve multiple customers with each having their own data. So any customer can basically only see their own data. If you don't have this challenge, you can ignore everything "customer related" from that documentation.

Regarding the endpoints:

- `.../comments/` lists all available comments (GET request) and allows a user to create a new one (POST)
- `.../comments/pk` shows a single comment (GET) and allows you to update (PUT) it or delete (DELETE) it 
- `.../item/comments/` lists all comments related to a single item, which in our software are "ideas"

**Comment by gaston4r** [comment]
We need more information about the expected json **response** from the server, its the same json for post a comment, upload a image, etc?
