### ISSUE TITLE
upvote is downvoting

### ISSUE THREAD

**Issue by nagthgr8** [Viima/jquery-comments#135]
When clicking on upvote the counter is moving backwards below is the code where needs fix

 if(commentModel.userHasUpvoted) {
                newUpvoteCount = previousUpvoteCount - 1;  //this should be previousUpvoteCount+1
            } else {
                newUpvoteCount = previousUpvoteCount + 1; //this should be previousUpvoteCount-1
            }

**Comment by nagthgr8** [comment]
oh ok i see this needs to be implemented ,

 set userHasUpvoted to true fist time when the same user upvotes that next time check if userHasUpvoted is true if so then downvote I guess that is what the code is doing
if(commentModel.userHasUpvoted) {
newUpvoteCount = previousUpvoteCount - 1; //this should be previousUpvoteCount+1
} else {
newUpvoteCount = previousUpvoteCount + 1; //this should be previousUpvoteCount-1
}

**Comment by jessenieminen** [comment]
Yes, user is only allowed to upvote once so the upvote button toggles the value. Thus `userHasUpvoted` needs to be set to true whenever the user has actually upvoted the comment. This works as intended.
