### ISSUE TITLE
mysql database demo

### ISSUE THREAD

**Issue by goodboy254** [Viima/jquery-comments#136]
Kindly can you give us some demo scripts of your plugin using a mysql database.
Am a newbie to this plugins things and we work well with working example.
I have tried to post data to the database but the parent field in my database is returning 0 even when am replyikng.
I have tried so hard to display data from my database using your documentation but nothing is displaying .
Please I beg help me with a mysql database php working demo of your plugin..

**Comment by goodboy254** [comment]
I hope you will reply to my issue very soon.

**Comment by jessenieminen** [comment]
We don't unfortunately have the resources to implement one soon but are open for pull requests for implementing such an example.
