### ISSUE TITLE
newest & oldest sorting under firefox

### ISSUE THREAD

**Issue by robenten** [Viima/jquery-comments#14]
Hi, we love this plugin. And we've found that if we change time format from  "2015-01-01" to "2015-01-01 05:07:47" will result in the newest & oldest sorting not working under firefox. But which works fine for rest of the browsers.

**Comment by jjtykkyl** [comment]
I believe that the new time format that you are using is not a standard format thus it's not working with Firefox. I also highly doubt that it would work with Internet Explorer. I recommend you to use standard formats and in your case this would mean adding 'T' in between the date and time, for example "2015-01-01T05:07:47". For other options, please check http://www.w3schools.com/js/js_date_formats.asp

**Comment by robenten** [comment]
Thank, Joona. It works fine now. By the way, is it possible to lazy load comments? For example if I have thousands of comments, it's unlikely to download at once.

**Comment by jjtykkyl** [comment]
I totally agree with you but unfortunately the feature you requested is not implemented as of now. It will be implemented at some point but at the moment I'm too busy with other projects. If you are willing to implement it yourself and create a pull-request , I'l be more than happy to check it out.
