### ISSUE TITLE
Attachment and comment?

### ISSUE THREAD

**Issue by Jojoshua** [Viima/jquery-comments#143]
While playing with the demo I noticed that you can't have a comment and attachment at the same time. Is this correct?

**Comment by CLothering** [comment]
I'd also like to know.

**Comment by s001dxp** [comment]
I've read through the code and one can either have an attachment or a comment, but not both

**Comment by jessenieminen** [comment]
Support for multiple attachments and having both text + attachments in a comment has now been implemented to the master branch and will be added to our next release.
