### ISSUE TITLE
Multiple attachments is not displaying for single comment

### ISSUE THREAD

**Issue by Sajalpal15** [Viima/jquery-comments#157]
Hi,
Thanks for the nice plugin.
It works fine except for one case. I am able to attach multiple files in a single comment but after uploading it's displaying three different comments.
Suppose I have attached **File1**, **File2**, and **File3** and as a comment, I have written: "I have uploaded File1, File2, and File3". After submitting the comments I am getting three different comments like
1. "I have uploaded File1, File2, and File3"
     `File1 downloadable Link`
2. "I have uploaded File1, File2, and File3"
     `File2 downloadable Link`
3. "I have uploaded File1, File2, and File3"
     `File3 downloadable Link`

But my requirement is:
1. "I have uploaded File1, File2, and File3"
     `File1 downloadable Link`,`File2 downloadable Link`,`File3 downloadable Link`

Can you suggest any solution?

**Comment by jessenieminen** [comment]
Support for multiple attachments has now been implemented to the master branch and will be added to our next release.
