### ISSUE TITLE
I have tried to install and didn't succeed...

### ISSUE THREAD

**Issue by PROgramJEDI** [Viima/jquery-comments#160]
I am using Django to build my website but I want to add a commenting system to it. so I tried to add the CSS styles to the head and the javascript scripts before the closing body tag, but it didn't work.

I also created a div container with these properties: id="comments-container" class="jquery-comments"

Can someone help, please?

**Comment by jessenieminen** [comment]
Unfortunately we don't currently have the resources to provide step-by-step instructions for every kind of a project.

However, I would suggest you take a look at DFR and use it to create a REST API to use with our library:  https://www.django-rest-framework.org/
