### ISSUE TITLE
set up database

### ISSUE THREAD

**Issue by sodonewith** [Viima/jquery-comments#163]
I feel a bit stupid, but wouldn't you need to know the name of the database / table?? I work with xampp - mysql. Reffering to the Backend/API Implementation, given at the end of https://viima.github.io/jquery-comments/ I have a no clue how to do this; in detail:
"item" - type "primary key related field" ???? - what is that??? I see this again and again in free open source: you write the greates software, but your users won't be able to use it. So frustrating. Also mySQL doesn't offer me type "file field" nor "serializer method field" nor "field" 

You seem so reluctant to give support here but wouldn't it make incredebly sense to write a script which then will configure the database?

**Comment by jessenieminen** [comment]
Unfortunately it's not that simple. You basically need to create an REST API.

There are many ways to do this, but here is a guide that could help you going forward: https://programminghistorian.org/en/lessons/creating-apis-with-python-and-flask
