### ISSUE TITLE
Packaging jquery-comments with Bower

### ISSUE THREAD

**Issue by SergioGregorutti** [Viima/jquery-comments#17]
Hi!

Thanks for this plugin. It seems pretty cool!

It would be nice if you packaging the plugin with Bower.

Thanks in advance!

**Comment by jjtykkyl** [comment]
I registered the package to bower so you should be able to install it with command "bower install jquery-comments". However, for some reason the bower won't ignore the files and folders I listed in bower.json so apologies for the unnecessary files.
