### ISSUE TITLE
I  need help how to set up complete on website for a html NOOB

### ISSUE THREAD

**Issue by THESTORMZ** [Viima/jquery-comments#185]
im rly new to this and this looks awsome i just dont understand how it work or how to set it up.

**Comment by jessenieminen** [comment]
Hi Ioniop, thanks for the comment! To use this on a website, you will also need to develop a backend to store the comments, files etc. If you don't have anything like that, it might be a bit of a challenging task for a complete beginner, and something we unfortunately can't help with ATM.

Here's a link to a Laravel implementation by one contributor: https://github.com/Viima/jquery-comments/issues/68#issuecomment-248864183

Hope this helps and best of luck with the project!
