### ISSUE TITLE
"Read only" mode

### ISSUE THREAD

**Issue by sadortun** [Viima/jquery-comments#21]
Hi!

For anonymous users, It would be nice to be able to use the plugin to display in "Read-Only" mode, having all the features (comment, reply, delete) disabled.

Have a good day,
Samuel

**Comment by jjtykkyl** [comment]
Thanks for participating this project! "Read-Only" mode is something that we have considered doing but is not the highest priority at the moment. Based on your pull-request, you seem to know what you are doing so feel free to create another pull-request out of "Read-Only" mode.

**Comment by sadortun** [comment]
Hi Joona,

Thanks ! I also have quite higher priorities, but it's on my infinitly growing todo-list! It probably will have to wait since i'll be away for the next 5 weeks.

There is 3 ways i see to implement this:
1. Hide all mutable controls
Can be done by adding a css class to controls: ex:   `.jquery-comments-mutable`
When `read-only` mode activated,   $('.jquery-comments-mutable').hide();`

2. Disable all mutable controls, but let them be visible.
Can be done by adding a css class to controls: ex:   `.jquery-comments-mutable`
When `read-only` mode activated,   $('.jquery-comments-mutable').disable();`

3. Leave mutable controls activated, but ask for credentials/login 
TBD using callbacks, ensuring the current state is preserved during the authentification process.

What do you think?
Samuel

**Comment by jjtykkyl** [comment]
I would just hide all the mutable controls: disabling them might confuse users as they don't necessarily know why the buttons are disabled and prompting for credentials can already be done with callbacks (check https://app.viima.com/viima/).

**Comment by jjtykkyl** [comment]
I'm happy to let you know that this feature has been implemented to version 1.1.0. The functionality can be enabled by setting the new variable "readOnly" to true
