### ISSUE TITLE
Can you tell me a little bit how i am suppose to stored the comments?

### ISSUE THREAD

**Issue by kimlym** [Viima/jquery-comments#24]
So recently I am working a rails project, and thinking about adding a comment function. Then i saw your work there which is super awesome. However, I'm not quite sure how I could save those comments data into the rails database.
It's rails 4 and database should be mysql or sqlite. Can you show me some really basic and simple example if you guys happen to know about that. May be even better if it could be done without son
Thanks

**Comment by jjtykkyl** [comment]
Unfortunately I'm not familiar with rails. What I recommend you to do is to create a REST api for your models. For example, if you have REST api for comments at URL "http://youdomain.com/api/comments", you can post a new comment in the "postComment" callback as follows:

$('#comments-container').comments({
    postComment: function(commentJSON, success, error) {
        $.ajax({
            type: 'post',
            url: '/api/comments/',
            data: commentJSON,
            success: function(comment) {
                success(comment)
            },
            error: error
        });
    }
});
