### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by untilyou89** [Viima/jquery-comments#25]
Hello.
I want to questions about 'pagination' data . Help !

**Comment by jjtykkyl** [comment]
I have used the utility function below for fetching new comments when the user has scrolled to the end of the comment container element:

```
function onScrolledBottom(el, callback, threshold) {
	var $el = $(el);
	threshold = threshold ? threshold : 0;

	$el.scroll(function() {
		if($el.outerHeight() + el.scrollTop >= el.scrollHeight - threshold) {
			callback();
		}
	});
}
````

The first parameter is the scrollable element containing all the comments. Then you can pass a callback function that fetches the next batch of comments from the server and appends the new comment elements into DOM.

**Comment by untilyou89** [comment]
@jjtykkyl  can you  build that feature in the new version ?

**Comment by jjtykkyl** [comment]
I can build a support for that feature but please note that you have to implement the pagination to your API as well.

**Comment by jjtykkyl** [comment]
I added a new function to the jquery-comments v1.1.0 named "fetchNext" that you can use for pagination. You still need to listen the scroll event on the element that is scrollable (body or .jquery-comments for example). The "fetchNext" function utilizes the the "getComments" callback where you need to implement the functionality on your end.

**Comment by untilyou89** [comment]
yeah.thank for support

**Comment by squallttthp** [comment]
hi @jjtykkyl, can you create a example use "fetchNext" with a button "load more", please ? I don't understand how can I use it for more comment get from server. Thank you so much !

**Comment by GRLeo** [comment]
@jjtykkyl @untilyou89 please tell how to call fetchNext function

**Comment by GRLeo** [comment]
I've got things working using this:

$('#comments').comments({...}});

$.data($('#comments').get(0), 'comments').fetchNext();

**Comment by burzum** [comment]
An example would be nice. And how do we paginate child comments? I don't want to display a huge amount of child comments but would prefer to show three and then the option to load more. Honestly I think this is something that should be part of the plugin.

**Comment by 222street** [comment]
Is there any plan to add infinite scrolling method at new version soon. 

Could you give me an example for infinite scrolling ?
