### ISSUE TITLE
Attachments feature

### ISSUE THREAD

**Issue by erichard** [Viima/jquery-comments#26]
Hello,

In my current project I need my user to be able to upload and attach files to theirs comments. 
Can this feature be easily added here ? Do you have any advices to do so ?

**Comment by jjtykkyl** [comment]
I'm adding this functionality to the library ASAP as there have been several requests about this matter. However, it's going to take some time since the library needs to support mobile use as well but hopefully I get it done this month. Please note that you still need to implement the attachment uploading to your backend to get it working.

**Comment by erichard** [comment]
@jjtykkyl Very pleased to hear that. 

My project is going live in january. Hope you will have time to release something. 
Tell me if you need help.

**Comment by jjtykkyl** [comment]
@erichard I've implemented the MVP of this feature to branch feature/attachments (https://github.com/Viima/jquery-comments/tree/feature/attachments) if you wish to start using it already. There's still a lot to do but the basic functionalities are in place.

The idea is that the attachments are treated as comments but they have two extra fields: "file" and "file_mime_type". You should define new callback function called "uploadAttachment" which takes the same parameters as the "postComment" callback. However, the "file" attribute provided in commentJSON is the actual file to be uploaded and it's up to your server logic to upload that file and transform the value of the attribute to the URL of the file instead. The commentJSON contains also the "file_mime_type" but you may want to validate this on your backend as well. This is used for showing preview of the file whenever possible (works only for images and video so far).

**Comment by erichard** [comment]
@jjtykkyl Can you rebase from the master branch with the reply button fix please ?

**Comment by erichard** [comment]
I use the File API from HTML5 to upload file on the server, it work great.
Great and fast work, thank you !

**Comment by jjtykkyl** [comment]
@erichard I can do even better, I just merged the functionality to master branch

**Comment by jjtykkyl** [comment]
I'm happy to let you know that this feature has been implemented to version 1.1.0. The functionality can be enabled by setting the new variable "enableAttachments" to true
