### ISSUE TITLE
unexpected page refresh when hitting reply button

### ISSUE THREAD

**Issue by spitzbubchen** [Viima/jquery-comments#27]
I want to use the comment box within a form. However, if do the following:

     <form>
            <div id="comments-container"></div>
     </form>

the entire webpage refreshes when the reply button is clicked.

Is seems that when the button is created type="button" is not specified....

**Comment by jessenieminen** [comment]
Thanks for contributing!

This seems to have been fixed recently with https://github.com/Viima/jquery-comments/pull/32
