### ISSUE TITLE
Posting new comments programmatically

### ISSUE THREAD

**Issue by andrewtroyan** [Viima/jquery-comments#29]
Hello. I'm working on project with real-time commenting section using your library. So when one client posts a new comment via UI, I need to post this comment to other clients programmatically (using SignalR). Tell me, please, is it possible? I'm beginner in JavaScript and jQuery so I would be grateful for a little hint. 
P.S. I've tried to add comment data manually with html, but it doesn't support all functionality.

**Comment by jjtykkyl** [comment]
This feature is not supported out-of-the-box. You can, however, copy the functionality from the postComment function:
'''
                var commentModel = self.createCommentModel(commentJSON);
                self.addCommentToDataModel(commentModel);
                self.addComment(commentModel);
'''
self being the jquery-comments instance. You can get reference to this instance with jquery as follows
'''
$('.jquery-comments').data('comments')
'''

**Comment by andrewtroyan** [comment]
Thank you!
