### ISSUE TITLE
is entry in jquery-comments valid

### ISSUE THREAD

**Issue by emaslow** [Viima/jquery-comments#3]
The following line 542 appears in jquery-comments.js:
            if(commentId = textarea.attr('data-comment')) {
Webmatrix labels it as an error as well the equivalent statement in the minimized version.
I am still working my way through an understanding of jscript and still have a long way to go, but my experience as  programmer tells me that this is a conditional statement that is always true because its argument merely sets the value of the variable.  This conditional statement serves no function. Should it be "==" ?, or am I misunderstanding something? 
There are also a dozen or more instances of variable lists ending with a unnecessary comma after the last entry which WebMatrix flags as errors. This is not a problem because the minimizing program seems to ignore them.

**Comment by jessenieminen** [comment]
Hi and thanks for the report @emaslow !

You're correct, it should indeed be "==". 

I've fixed the issue in a new commit here: https://github.com/Viima/jquery-comments/commit/fa36d65c1b8f5e555ce1de38676ea8fa4a339321

As for the errors regarding line unnecessary commas in WebMatrix, it's true that they don't really affect anything. I also think that those errors are a result of the WebMatrix syntax checker not realising that there might be empty rows within lists. Could you confirm if those errors are coming from rows immediately followed by empty rows?

**Comment by emaslow** [comment]
Thank you, jessenieminen, I did assume  a typo. 
The commas only occur for the last item in a given list, no empty rows. But, it is that they are not needed for the standard and not necessarily wrong. Most interpreters just ignore them. WebMatrix is just picky. No problem when you realize this, but a bit of a nuisance. It's easier to just delete the commas than to ignore them.
