### ISSUE TITLE
Limit comment text

### ISSUE THREAD

**Issue by unsruns** [Viima/jquery-comments#36]
Hello Viima,
how can I limit commenting text to 1000 char only.

thanks for this amazing plugin.

**Comment by jessenieminen** [comment]
Hi @unsruns , thanks for your inquiry and interest in jquery-comments. 

Limiting comment length is a feature that we haven't (at least yet) built directly into the plugin. This is, however, really simple to achieve as we offer postComment and putComment callbacks ([see  the documentation](http://viima.github.io/jquery-comments/#link-3-6)) that'll let you do client side validation on the comments by just checking the length of the comment description before posting it to the server with something like:
`if(commentJSON['description'].length > 1000) { alert('Maximum length for comments is 1000 characters.')} else { postCommentToServer(); } `
With, of course, the alert function swapped to whatever notification system you already have in place in your app.

This could also be a somewhat useful feature for jquery-comments in general so if you're planning to do this, we'd be delighted to see a pull request from you, as long as you make sure the feature can also be turned off via the settings.

However, just as a reminder, make sure you're also validating the comment length in your backend among other model validations for both security and robustness. Client side validation is only good for giving the user a great UX.
