### ISSUE TITLE
comments data not saved to file

### ISSUE THREAD

**Issue by rewerb** [Viima/jquery-comments#38]
Hi, 

Comments on my site are not saved to comment-data.js file ones posted or edited. 
Do I need anything more to be configured to have this? Any permissions to data file or something else?

I cannot find it in your docs.

Best regards
Rado

**Comment by jessenieminen** [comment]
Hi Rado,

Thanks for your interest in jQuery-comments!

comment-data.js is only a placeholder file for loading the demo data, not a backend or storage solution. You'll actually need to implement that backend for storing the comments yourself.

I know there's an open source project called node-comments, which aims to create a compatible backend for jQuery-comments, you can see the project here: https://www.npmjs.com/package/node-comments.
