### ISSUE TITLE
jQuery.browser() removed in jQuery 1.9 and still used in Init function of jquery-comments

### ISSUE THREAD

**Issue by Glursh** [Viima/jquery-comments#39]
Hi !

When looking on jQuery changes, I saw that browser() function has been removed in version 1.9.

However, this function is still used in the last release of jquery-comments to detect mobile device, in Init function, line 200.

What's your opinion about the fact that jquery-comments is compatible with version 1.9 of jQuery ?
(Dependencies say jQuery >= 1.9.0)

(Sorry for my English and thanks for your work)

Yannick

**Comment by jjtykkyl** [comment]
The jquery-comments is not dependent on $.browser() function as it defines the function if it wasn't available. If you look at the initialization, you see that function is defined as follows:
````
jQuery.browser = jQuery.browser || {}
````
Initialising an empty dictionary will act as a fallback if the jQuery version used did not provide the jQuery.browser -function
