### ISSUE TITLE
Any new posts, edits, deletes are not updated.

### ISSUE THREAD

**Issue by RBurnikell** [Viima/jquery-comments#43]
When i try to comment and delete, all that stuff, it works fine. But when i refresh the page all the changes made reset to what was on the page originally.

I have used the code provided in the tutorial on my own, but not sure if i am missing something that saves.

Putting it out there, i am extremely new to jquery.

**Comment by jjtykkyl** [comment]
You need an existing backend to save your comments, please see https://github.com/Viima/jquery-comments/issues/38
