### ISSUE TITLE
More than 2 levels of nesting?

### ISSUE THREAD

**Issue by blimey85** [Viima/jquery-comments#46]
Maybe I'm just missing a configuration option, but is it not possible to do more than 2 levels of comments? In my setup I have root comments and when I reply, I get one level of nesting, so two levels total. Then when I click to reply to the first reply, which should create a comment that's three levels deep (root > reply > reply of reply) it looks like it's a reply to the original comment rather than a reply to the reply. Am I just doing something wrong? I noticed this was compared to Disqus but I just checked and Disqus definitely allows replies on replies. Not sure if there is a limit to how deep it will allow you to go.

On the back-end I have comment setup so I can go an unlimited number of levels and I passed in comments with parents that were replies... meaning comment is 1, reply was 2 with a parent of 1, reply of reply was 3 with a parent of 2, and so on, and it displays them as two levels. So they do all display, but just with proper levels.

In the even that only two levels are supported, is this something that could be added? I'd be willing to work on the functionality as it's something I need for my current project.

**Comment by blimey85** [comment]
Disregard this. I was confused because when I click to reply to a reply that has already been replied to, (did that make sense?), the reply box does not show under the reply I am trying to reply to, but at the end of the replies. I also didn't notice the reply icon indication that some replies are nested deeper than two levels. I'm going to investigate customizing my CSS to show deeper nesting but overall, with the exception of the reply box not showing where I would expect it to be, it's working great.

**Comment by jessenieminen** [comment]
Thanks for your comments, you are indeed correct in the sense that we do support multiple levels of replies to comments and there's no limitation for how long that can go on.

We initially considered whether to implement showing these replies with indentation even when they have a nesting level of more than 2 but quickly realised that that approach doesn't really work at all on responsive sites and mobile, which are the key reasons for implementing this library in the first place.

Thus, if you prefer to, you can create custom CSS for this purpose to override default behaviour but if you were planning to support mobile users, we'd recommend against that.
