### ISSUE TITLE
Conflicting comment IDs followed by deleting and then posting. Comments array keys need to be renewed after each delete.

### ISSUE THREAD

**Issue by wictorio** [Viima/jquery-comments#47]
I have noticed that the comment IDs are not being reloaded after when one or more is deleted from the whole comments array which results with conflicting IDs. Example:
```
Current comment IDs  = 1,2,3
Delete ID 2 = 1,3
Post new comment = 1,3,3
```
It looks like it's counting the elements alright only it doesn't renew the array keys.

**Comment by jessenieminen** [comment]
Hi,

I'm not sure what you're trying to really do here but just to clarify jquery-comments doesn't try to update the IDs of your models or validate them for conflicting IDs, nor should it do so. 

That kind of things should always be handled in you backend and/or API for a number of reasons, mainly related to security and data integrity.

Your API is thus responsible for providing the updated IDs, not jquery-comments.

**Comment by RedPointMS** [comment]
@jessenieminen I think this issue shouldn't be closed. There is indeed a problem with creation of new comment after deletion. Here are the steps to reproduce:

1. Delete an existing comment
2. Without closing the window, add a new comment

The new comment is created with internal id (in commentJSON) of the existing last comment. So for example if I had ids: c1, c2, c3 and deleted c2, after adding new comment the new one has id c3. Thus this leads to duplication of c3. As far as I know jquery-comments doesn't expose any function to reindex the internal ids.
Ami I missing anything?

**Comment by MarksEliel** [comment]
Post exemple code please
