### ISSUE TITLE
Suggestion: Use Font Awesome Icon instead of profile picture

### ISSUE THREAD

**Issue by webbird** [Viima/jquery-comments#5]
If you not give a profile picture url, a "broken image" symbol is shown. It would be nice to have a default (maybe encoded as Base64), and to allow the usage of Font Awesome Icons (fa fa-user).

**Comment by jessenieminen** [comment]
Hi @webbird !

Thanks for the suggestion! It's indeed a good idea to use FA instead of the image file for users without a separate profile picture. We'll make the change with the next release of v.1.0.2!

**Comment by webbird** [comment]
You could also think about using Gravatar. I have now written a comments module from scratch and use Gravatar, it also allows to create default images in different ways. Requires to have an email address though.

**Comment by jessenieminen** [comment]
Thanks for the suggestion @webbird !

We're actually already using Gravatar in our main product in combination with jquery-comments. It's a great addition for automatically adding profile pictures for the users who have a Gravatar. 

Still, I think managing the profile picture of the user should be left to the application logic and the backend as an architectural best practice. I can't think of a case where it would be desired to manage this just in the front end. Thus we're not planning to add Gravatar support for the library.

**Comment by jjtykkyl** [comment]
I'm happy to let you know that this feature has been implemented to version 1.1.0

**Comment by webbird** [comment]
Great news, thank you very much.
