### ISSUE TITLE
Sorting Newest, Oldest and Popular is not working on Chrome

### ISSUE THREAD

**Issue by aliefmaksum** [Viima/jquery-comments#50]
I'm confused. I have implemented the callback and everything is working fine except the newest, oldest and popular sort. It's working fine in Firefox, but in Chrome the sort is not working. I'm using ISO 8601 time format, so I think the date format should be okay on multiple browser. Could you help figure me out what's wrong? I've spent 2 days without any luck :(

My site is: www.zetizen.com, in case you need to see the problem..

**Comment by aliefmaksum** [comment]
Never mind.. I try to use the non minified version and it works fine.. 
I think you should also update the jquery-comments.min.js in the repository :)

**Comment by jessenieminen** [comment]
Thanks for the comment, we'll make sure to update that in a couple of weeks once we get to work on this library again :)
