### ISSUE TITLE
Firefox Issues

### ISSUE THREAD

**Issue by mstojanovv** [Viima/jquery-comments#51]
Hi.

Great plugin.
There is some Firefox issues
http://oi67.tinypic.com/m9o8ko.jpg

The plugin auto add new line but becuase is together with the text the new line shows as text only.
Also the Oldest button dont work well.

Any suggestions?
Regards.

**Comment by jessenieminen** [comment]
Hi, 
thanks for your comment!

I can't seem to reproduce any of those issues with Firefox (or any other browser for that matter). Could it have something to do with your implementation?

If you could provide us with Codepen or similar that reproduces the issue, we could take a look at this in a couple of weeks when we're going through the current issues and that one pull request for this library.

**Comment by mstojanovv** [comment]
Hi.

I cant find the problem in the implementation, becuase seems like browser problem becuase works on Chrome and not on Firefox.
Here is an preview http://goo.gl/S4Kj5l - Projects->Project->Discussions - Click on some discussion.

I already tested on Chrome is working good but not on Firefox.
Will be appreciated if any idea how this can be fixed..
Thanks.

**Comment by jessenieminen** [comment]
Hi, thanks for getting back! The link returns 404, could you try again?

**Comment by mstojanovv** [comment]
Hi.

I updated the link. Initialy was posted as 404 the i change it.

**Comment by jessenieminen** [comment]
Thanks. I can confirm that I could replicate the bugs in the pic in your code but still can't do the same in any of my implementations with the latest code so I think this must be an implementation specific thing.

A quick look at the data in your comment model shows that your dates are not the standard string representation with timezone that Date() is looking for so I'm not at all surprised that the sorting doesn't work. Chrome and other browsers just work around the issue whereas Firefox doesn't. Please change the format returned by your API to fix the issue.

As for the issue with the <br> element, I'd suspect a double escape somewhere in your code prior to or after parsing the date.

**Comment by mstojanovv** [comment]
Hi.

Thanks for the reply.
I was able to fix the new lines problem.. About the 1 hour in the past this is based on timezone thats why showing like this..

About the date i'm passing the dates via the API as Y-m-d H:i:s but as i can see Y-m-d H:i:s is not accepted right? Should be just Y-m-d?  If yes in this case the sorting wont be 100% accurate..
Ex if there is 5 comments with the same date in format Y-m-d how will be sorted then?

Also when i try to pass it like Y-m-d its not accurate again.

Thanks.

**Comment by jessenieminen** [comment]
Good to hear! Yes, milliseconds are a good way to do it.

Usually APIs have either milliseconds or then use the Javascript native date format: "2016-05-13T06:21:28.961Z". In both of these cases, you should probably save these as UTC time and then have the browsers convert the times to the correct timezone for each user.
