### ISSUE TITLE
Could we have a feature which load/refresh the comments every 5 seconds

### ISSUE THREAD

**Issue by cooperyuan** [Viima/jquery-comments#53]
I am new to Jquery, but realized this plugin is pretty cool. Now I would like to reload/refresh the comments container every 5 seconds, googled and tried, but the experience is not so good.

What I am looking for is that only some new comments being added or removed, not the whole div or page being refreshed.

Thanks!

**Comment by jjtykkyl** [comment]
This is a feature that should be imlemented using web sockets instead of polling the API every X second. Moreover, it should be implemented on the application's end, not the other way around. The web socket implementation is highly dependent on the application for which reason it cannot be implemented directly to the jquery-comments. However, you can utilize the "createComment" and "deleteComment" functions if you end up implementing the feature to your application.

**Comment by cooperyuan** [comment]
Thanks Joona, but createComment and deleteComment will cause the UI
refresh, what I am looking for is the comment area automatically add new
comment and hide removed comments without refresh, is there any suggestion?

**Comment by jjtykkyl** [comment]
I'm not quite sure what do you mean by the UI refresh as neither delete nor create rebuilds the DOM but only the one specific element is manipulated.

**Comment by cooperyuan** [comment]
Sorry I didn't express clearly, I mean the comment area could automatically
load new comments, the visual effect is a new comment is being inserted at
the top without flashing. :-)

**Comment by jjtykkyl** [comment]
Still no sure what do you mean by flashing, are you sure you are not reloading the plugin on a addComment or deleteComment callback? If you look at the source (addComment -function) you can see that only the created element is added to DOM without UI refresh.

**Comment by cooperyuan** [comment]
I think you are right, add/deleteComment is perfectly working for me.
Thanks!

On Wed, Jul 13, 2016 at 3:27 PM, Joona Tykkyläinen <notifications@github.com

**Comment by jvosloo** [comment]
Hi. I have successfully implemented calls to createComment and removeComment to programatically update the comments widget. What I'm having trouble with is updated comments.... as calling the putComment method doesn't seem like a viable option. Any ideas?
