### ISSUE TITLE
Documentation table is too narrow

### ISSUE THREAD

**Issue by JanWielemaker** [Viima/jquery-comments#55]
The table at e.g., http://viima.github.io/jquery-comments/#link-3-6 is too narrow, such that the right side of the description is hidden.  You then have to go to the end of the table to scroll it horizontally and find your way back to where you were ...  Rendering is the same on FF and Chromium (Ubuntu).

**Comment by jjtykkyl** [comment]
You're absolutely right, we'll fix it as soon as we have time.
