### ISSUE TITLE
How created_by_current_user is supposed to work?

### ISSUE THREAD

**Issue by RedPointMS** [Viima/jquery-comments#56]
Hi,

I just need a clarification. I am not sure how the `created_by_current_user` field is supposed to work. When I create a new comment and store in DB commentJSON array with default value `true`, then I can see `You` as the user. However when any other user retrieves the comments, they also see `You` for comments that I created. Does it mean that each time the commentJSON is retrieved, the array must be checked for which user created it and set the `created_by_current_user` to `false`?

**Comment by jjtykkyl** [comment]
The created_by_current_user field should be used as a read-only field and the API you're using should provide this information for each comment. This field is then utilized for showing "You" instead of the name of auther as well as enabling update and delete functionalities for own comments.
