### ISSUE TITLE
Attachment Upload fakepath

### ISSUE THREAD

**Issue by valula** [Viima/jquery-comments#58]
Hi,
thanks for such a great plugin, works very well.
I have some issue with uploading image to server, I need convert image to dataUrl (base64) and send it to server, but the path created by plugin is wrong, so I cant reach the image. Maybe I am doing something wrong, can you please check it out?
Image attached with console print screen, 
Thanks!
V.
![2016-07-19 07_41_46-greenshot](https://cloud.githubusercontent.com/assets/20341405/16939032/642563c0-4d86-11e6-896b-81b398834daa.jpg)

**Comment by jjtykkyl** [comment]
You need to upload the image wrapped to FormData object like presented in the documentation http://viima.github.io/jquery-comments/#link-3-6. You also need to se the contentType and processData parameters to false.

````
            // Create form data
            var formData = new FormData();
            $(Object.keys(commentJSON)).each(function(index, key) {
                var value = commentJSON[key];
                if(value) formData.append(key, value);
            });

            $.ajax({
                url: '/api/comments/',
                type: 'POST',
                data: formData,
                cache: false,
                contentType: false,
                processData: false,
                success: function(commentJSON) {
                    successfulUploads.push(commentJSON);
                    serverResponded();
                },
                error: function(data) {
                    serverResponded();
                },
            });
````

**Comment by valula** [comment]
Thank you very much! formData worked!

On Wed, Jul 20, 2016 at 9:32 AM, Joona Tykkyläinen <notifications@github.com
