### ISSUE TITLE
[Google Chrome] Cannot read property 'parent' of undefined

### ISSUE THREAD

**Issue by gempain** [Viima/jquery-comments#69]
Hello,

When comments are added to the `commentsById` array of the plugin, it ay happen that the parent comment is not yet present, which causes a `Uncaught TypeError: Cannot read property 'parent' of undefined` in function `getOutermostParent`, since `this.commentsById[parentId]` is undefined.

This does not happen all the time, and really depends on the order in which comments are processed. However, after analysing the code, it turns out that the way parents are added is prone to errors. Things work fine on Safari, but I have honestly no idea why. 

In order to add parents properly, all comments should be appended to `commentsById` and then they should be re-processed to update parents / children lists. My workaround so far is to replace

```
addCommentToDataModel: function(commentModel) {
    if(!(commentModel.id in this.commentsById)) {
        this.commentsById[commentModel.id] = commentModel;

        // Update child array of the parent (append childs to the array of outer most parent)
        if(commentModel.parent) {
            var outermostParent = this.getOutermostParent(commentModel.parent);
            outermostParent.childs.push(commentModel.id);
        }
    }
},
```

by

```
addCommentToDataModel: function(commentModel) {
    if(!(commentModel.id in this.commentsById)) {
        this.commentsById[commentModel.id] = commentModel;
    } else {
        // Update child array of the parent (append childs to the array of outer most parent)
        if(commentModel.parent) {
            var outermostParent = this.getOutermostParent(commentModel.parent);
            outermostParent.childs.push(commentModel.id);
        }
    }
},
```

and then in function `fetchDataAndRender`, call

```
$(commentModels).each(function(index, commentModel) {
    self.addCommentToDataModel(commentModel);
});
```

twice:

```
$(commentModels).each(function(index, commentModel) {
    self.addCommentToDataModel(commentModel);
});
$(commentModels).each(function(index, commentModel) {
    self.addCommentToDataModel(commentModel);
});
```

I know it is a poor workaround, but at least it works for now.

All the best.

**Comment by masonlr** [comment]
Writing here in case this helps someone else: I had a similar problem but the issue was that my database backend returned  `parent:""` rather than `parent:null`. This tripped up the do/while construct in `getOutermostParent `.

**Comment by anhkhoi** [comment]
The same issue for me

**Comment by s001dxp** [comment]
this is still an issue.

**Comment by latuminggi** [comment]
imho it's all because of pagination we have, since default ordering is newest comment and if we load first page where the child comments are newer than its parent, and the parent seemed not included on the first page data set.
so i think we should load more data with wider range/interval. for example if the default per page is returning 10 comments, we should return more comments data to be loaded, but you should prepare your API for it, here's my workaround:

```js
// function getCommentsUrl for handling Ajax URL easily
function getCommentsUrl(page, per_page) {
    return '/your/api/getComments?per_page='+ per_page +'&page='+ page;
}

$('#comments-container').comments({
    ...,
    getComments: function (success, error) {
        var page    =  1; // initial page number
        var perPage = 10; // comments per page

        $.ajax({
            url: getCommentsUrl(page, perPage),
            contentType: 'application/json',
            dataType: 'json',
            error: error,
            success: function (comment) {
                try {
                    success(comment.data);
                } catch (err) {
                    // Update Ajax URL and increment per page for wider range
                    this.url = getCommentsUrl(page, perPage++);
                    $.ajax(this); // Reload Ajax with new URL
                }
            }
        });
    }
    ...,
});
```
for me, this working just fine since if it catch the error on "success" will eventually to reload with wider range/interval of data set until there's no exception any longer. if you have trouble with this way, feel free to reply me here
