### ISSUE TITLE
Bug in the final version

### ISSUE THREAD

**Issue by CaiqueJhones** [Viima/jquery-comments#7]
Version for download on the site contains an error in time to comment. Check the console: Cannot read property 'content' of undefined

**Comment by timthepig** [comment]
I'm also experiencing the same issue.  I'll take a further look.

**Comment by CaiqueJhones** [comment]
I downloaded the version that is on the sample page, http://viima.github.io/jquery-comments/demo/
http://viima.github.io/jquery-comments/demo/js/jquery-comments.js
It worked

**Comment by jessenieminen** [comment]
There was indeed a bug with the latest commits, a small change we made in #6 was the reason for this so we reverted the changes made there.

Now it should work again.
