### ISSUE TITLE
Need Suggestion : What type of database table will be best to use your commentbox ?

### ISSUE THREAD

**Issue by subodhcjoshi82** [Viima/jquery-comments#71]
I am using MySql for my web-application as you know MySql does not support  Hierarchical Data and we have to use extra table where we should make entry for 

> CREATE TABLE `posts` (
> `post_id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
> `user_id` int(7) unsigned NOT NULL,
> `post` varchar(45) COLLATE utf8_bin NOT NULL,
> `content` text COLLATE utf8_bin,
> `ts` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
> PRIMARY KEY (`post_id`,`user_id`),
> KEY `post_id` (`post_id`),
> KEY `user_id` (`user_id`),
> CONSTRAINT `user_id` FOREIGN KEY (`user_id`) REFERENCES `users` (`user_id`) ON DELETE NO ACTION ON UPDATE NO ACTION
> ) ENGINE=InnoDB AUTO_INCREMENT=952 DEFAULT CHARSET=utf8 COLLATE=utf8_bin;

Second Table called  closure table 

> CREATE TABLE `comment_hierarchy` (
> `ancestor` int(10) unsigned NOT NULL,
> `descendant` int(10) unsigned NOT NULL,
> `depth` tinyint(3) NOT NULL DEFAULT '0',
> PRIMARY KEY (`ancestor`,`descendant`),
> KEY `descendant` (`descendant`),
> CONSTRAINT `comment_hierarchy_ibfk_1` FOREIGN KEY (`ancestor`) REFERENCES `posts` (`post_id`),
> CONSTRAINT `comment_hierarchy_ibfk_2` FOREIGN KEY (`descendant`) REFERENCES `posts` (`post_id`)
> ) ENGINE=InnoDB DEFAULT CHARSET=utf8

Is this approach fine ? or you have any suggestion which will best suits for your component  ?

**Comment by jessenieminen** [comment]
I've added information about our database/API design to the documentation: http://viima.github.io/jquery-comments/#link-4. Quite easy to implement even without any hierarchical structure.
