### ISSUE TITLE
I can´t use it

### ISSUE THREAD

**Issue by JessicaPuebla** [Viima/jquery-comments#73]
I have tried to put the code on my project but I get this error:

> `TypeError: $(...).comments is not a function`

**Comment by subodhcjoshi82** [comment]
Look like your method call before the library initialize that why you are getting this issue..I tried same library its worked fine without any issue .

**Comment by JessicaPuebla** [comment]
Thanks for the response. I took the same example of index.php file and I found that it had the same issue, then I replaced the jquery-comments.js version 1.1.2 file with version 1.1.0 that I got from the demo(view-source:http://viima.github.io/jquery-comments/demo/).

I think the last version is is the suggested but I could not initialize my project. The version 1.1.0 works well for me.

**Comment by subodhcjoshi82** [comment]
I tested Latest code in my work-space with JSF/Tomcat/Java and its worked fine Just share your implementation or first try individual code without integration and see if you are getting same error.
