### ISSUE TITLE
Posting details of parent

### ISSUE THREAD

**Issue by KG20** [Viima/jquery-comments#76]
Hi,
I searched all the issues and documents and as I am new to web development I cannot figure out how
to get the id of the parent element when a reply is posted?
Also, when I get the comments all the names are coming as "you" (I directly saved comments in the database to test my get function), I am not sure why is that happening.
Also, if someone hasn't "edited" a comment will it always come as "invalid"?
This is my database table and screenshot of comments:

![mysql](https://cloud.githubusercontent.com/assets/22630537/19226180/6d6de634-8ec5-11e6-9d18-244b6313b4a3.png)
![comments](https://cloud.githubusercontent.com/assets/22630537/19226181/7699c390-8ec5-11e6-8fc4-9509dca610a4.png)

Thank you!

**Comment by subodhcjoshi82** [comment]
Table design could be one reason my assumption

**Comment by krutigoyal20** [comment]
Table design according to this question (atleast for posting) is secondary, as i dont know how to code this in jquery/php, from where it will go to sql.
As for "you" and edited date issue, how is table design be at fault?

**Comment by jessenieminen** [comment]
You need to provide the library with that information and the best way to do this would be to provide  the information via the API. I've updated the documentation to show an example of an API which has all the required fields. Then you simply need implement those to your backend: http://viima.github.io/jquery-comments/#link-4
