### ISSUE TITLE
Angular Support

### ISSUE THREAD

**Issue by chanduk040** [Viima/jquery-comments#78]
Dear Team,

I am using this plugin on one of my project. Now, I was asked to integrate my project into another application which is developed in Angular. 

Hence I would like to ask does this plugin supports for angular as well or else atleast in future? If no, Can you please help me in this?

Regards,
Chandu

**Comment by GInkida** [comment]
Actually, you can use it in any angular application without a problem. Am using it with 1 version and everything goes fine.

**Comment by chanduk040** [comment]
@GInkida , Thank you for replying. Fortunately I am also using Angular 1.5 version. 

Could you please share the piece of code how you initialize the plugin with all commenting events.

Regards,
Chandu

**Comment by GInkida** [comment]
@chanduk040 , Sorry for being too late, but am not a specialist at angular or js. Am using it inside angular controller in getComments function (shortened):

```
function getComments(alias) {
            ...

            $http.get(url).success(function(data) {
            
            $('#comments-container').comments({
            // readOnly: read_only,
            // currentUserIsAdmin: admin,
            // profilePictureURL: avatar,
            getComments: function(success, error) {
                success(data);
            },
            postComment: function(commentJSON, success, error) {
                var comment = JSON.stringify(commentJSON);
                $http.post('api/' + alias + '/comment', comment).
                success(function(data) {
                  success(data);
                  }).
                  error(function(data) {
                  toastr.error('Authorization problem');
                  });
            }
            });

            }).error(function() {
            toastr.error('No comments');
            });
}
```

**Comment by chanduk040** [comment]
@GInkida , Not at all late GInkida. Thanks for sharing the code. I will try to implement same. Thanks again for your help.

Regards,
Chandu
