### ISSUE TITLE
Display Html data from disqus to jquery-comments

### ISSUE THREAD

**Issue by asmplease** [Viima/jquery-comments#88]
I am trying to display html data in the comments. Issue is it shows me html in text format with <p> and other tags etc. How can i avoid this.  Sample string is given bellow.
`<p>Ramdas and Shivaji's perception of \"Bhavāni incarnate as India\" and Sri Aurobindo's patriotic expression in his  100 verse sanskrit poem Bhavāni Bharati is very significant:</p><p><a href=\"http://surasa.net/aurobindo/bhavani.php\" rel=\"nofollow noopener\">http://surasa.net/aurobindo/bh...</a></p><p>Also the revolutionary blueprint and programme to free India by an order of Bhakts and Karamyogis was called by Sri Aurobindo as Bhavāni Mandir:</p><p><a href=\"http://www.searchforlight.org/lotusgroove/Sri%20aurobindo,mother,integral%20yoga,transformation.freedom,Bhawani%20Mandir.htm\" rel=\"nofollow noopener\">http://www.searchforlight.org/...</a></p>`

**Comment by jessenieminen** [comment]
You can remove any and all HTML tags quite easily with JavaScript prior to passing them on the library. See for example: https://stackoverflow.com/questions/822452/strip-html-from-text-javascript
