### ISSUE TITLE
Enable Send button programmatically?

### ISSUE THREAD

**Issue by bobrinch** [Viima/jquery-comments#90]
I would like to ask for a new feature in jquery-comments.

In my web-app I want to show comments. When the user has typed a message, I want to prompt for them to login via facebook before the comment is saved. This login is done in a popup. When the user has logged in, I'd like for them to be able to click the Send button on the comment they just typed. However, this Send button is disabled, until you type something else in the comment box. This may not be intuitive to the user.

Could you perhaps add a function in your plugin, so that I can enable the Send button programmatically?

**Comment by jessenieminen** [comment]
Hi @bobrinch !

We've implemented a feature in our own application that requires the user to log in when they click send. In our opinion, the ideal way to handle this is to ask the user to log in only once they've already clicked send and then to send the comment automatically once they've successfully logged in. Other forms of implementing this only result in a more unintuitive and difficult user experience and we aren't thus planning on supporting them.

Thus you simply need to add the code that checks if a user is logged in and if not, forces them to log in, to your `postComment` callback before actually posting the comment to your backend.
