### ISSUE TITLE
Improving sorting with hours and minutes

### ISSUE THREAD

**Issue by Taxman972** [Viima/jquery-comments#95]
I would like to sort comments with more precision cause currently all comments of the same day aren't sorted correctly.

**Comment by jessenieminen** [comment]
Haven't seen this happen yet. It's likely that your dates are in non-standard format, in which case different browsers can interpret and parse dates differently. I would suggest you to change your API so that it uses the standard date format, .e.g. `2017-07-12T11:15:42.207860Z`.
